### PR TITLE
Added a new groups attribute, hidden for now.

### PR DESCRIPTION
**Pull request by mar235av**

### CODE REVIEW

**Review by jprosser — APPROVED** [review]
Looks good to me

**Comment by mar235av** [comment]
Needed an additional update - when I moved this attribute from the displayed to hidden section, I forgot to add the reqHidden attribute to make it hidden. Fixed that.

**Comment by mar235av** [comment]
New updates applied.
1. Updated the user interface with a copy of the custom handling for the groups attribute.
2. Updated the Javascript with code to support the new groups attribute.
3. Changed the attribute.xml so that this new attribute will be publicly visible.

**Review by jprosser — APPROVED** [review]
From a not too careful read, looks good!

**Pull request merged**
